- name: set up webserver on all hosts
  hosts: all
  become: yes
  tasks:
          - name: "install apache2"
            apt: 
              name: "apache2"
              state: "present"
          - name: "deploy custom html"
            copy:
              dest: /var/www/html/index.html
              src: apache-simplilearn.html
