# Create 3 files with content "hello from simplilearn" on the web host
# /tmp/myfile
# /etc/filefromansible
# /root/anotherfile
#


---
- name: "create files"
  hosts: web
  become: yes
  vars:
          file_info:
            name: myfile 
            text: hello from devops
  tasks: 
    - name: "create file1"
      copy:
              dest: "/tmp/{{ file_info.name }}"
              content: "{{ file_info.text }}"
    - name: "create file2"
      copy:
              dest: "/etc/filefromansible"
              content: "{{ file_info.text }}"
    - name: "create file3"
      copy:
              dest: "/root/anotherfile"
              content: "{{ file_info.text }}"
