--- #Install Java and Jenkins
- name: "Install Java and Jenkins"
  become: yes
  hosts: web
  tasks:
          - name: "Installing java"
            apt: 
              name: "openjdk-17-jdk"
              state: "present"
          - name: "Prepare for installing jenkins"
            shell: "curl -fsSL https://pkg.jenkins.io/debian/jenkins.io.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null && echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc]
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null"
          - name: "Installing ca certificates"
            apt:
                    name: "ca-certificates"
          - name: "Installing jenkins"
            apt:
              name: "jenkins"
              state: "present"
              update_cache: yes
